packages:
  - packages/assets

catalog:
  "@supabase/supabase-js": ^2.48.1
  "@t3-oss/env-nextjs": ^0.13.8
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  "@types/node": ^22.10.1
  "@vercel/postgres": ^0.10.0
  "@vitest/coverage-v8": ^1.4.0
  "@vitest/ui": ^1.4.0
  bcryptjs: ^2.4.3
  dotenv: ^16.4.5
  drizzle-kit: ^0.30.0
  drizzle-orm: ^0.36.4
  drizzle-zod: ^0.5.1
  eslint: ^9.12.0
  pg: ^8.11.3
  postgres: ^3.4.3
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  tsx: ^4.19.4
  typescript: ^5.6.3
  vitest: ^1.4.0
  zod: ^3.23.8

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.7
    "@types/react-dom": 19.0.3
